name: Bug report
about: Create a report to help us improve
title: "[Bug] xxxxxx"
labels: ["bug"]
assignees:
  - boyander
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      placeholder: Tell us what you see! A clear and concise description of what the bug is.
    validations:
      required: true
  - type: markdown
    id: bug-steps
    attributes:
      label: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: markdown
    id: bug-expected
    attributes:
      label: Also tell us, what did you expect to happen?
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: bug-browser
    attributes:
      label: "Browser / OS"
      description: "How often do you or others encounter this bug?"
      placeholder: "Chrome 128.0.6613.85 / macOS Sonoma 14.5"
    validations:
      required: true
  - type: markdown
    id: bug-screenshots
    attributes:
      label: If applicable, add screenshots to help explain your problem.
