import { existsSync } from "fs";
import { readFile, rename, rm, writeFile } from "fs/promises";
import { renameSync, rmSync } from "fs";
import path from "path";
import { log } from "../../../../log";

/**
 * Transparent deterministic-buildId for Next.js apps
 * (arch/deploy/version-skew-coexistence.md, Fase 1).
 *
 * Next reads no env var for its buildId — the only deterministic source is
 * `generateBuildId` in the user's next.config. Rather than asking users to
 * edit their config, the buildpack wraps it for the duration of `next build`:
 * the original file is renamed aside and replaced by a generated wrapper that
 * resolves it (object | function | promise | async) and adds a
 * `generateBuildId` reading FAABLE_DEPLOY_ID — ONLY when the user doesn't
 * define their own.
 *
 * The wrapper is self-contained (no imports beyond the original config): the
 * user's node_modules has no faable packages.
 *
 * Restoration is guaranteed: `restore()` runs in the caller's finally (before
 * the docker build, so `COPY . .` packages the original config — `next start`
 * loads next.config at runtime too), and a signal handler covers Ctrl-C
 * mid-build. `next.config.ts` is skipped with a warning (it needs Next's own
 * TS loader; not wrappable from a JS wrapper).
 */

const CONFIG_FILES = ["next.config.js", "next.config.cjs", "next.config.mjs"];
const ORIGINAL_PREFIX = "next.config.faable-original";

export interface WrappedConfig {
  restore: () => Promise<void>;
}

const wrapperBody = (
  originalFile: string | null,
  flavor: "cjs" | "esm"
): string => {
  const resolver = `
const resolveConfig = async (original, phase, args) => {
  let config = original && original.__esModule ? original.default : original;
  if (typeof config === "function") config = config(phase, args);
  config = await config;
  config = config || {};
  if (config.generateBuildId) return config; // user-defined wins, never override
  return {
    ...config,
    // Deterministic buildId = platform deployment id (build id ≡ runtime id).
    generateBuildId: () => process.env.FAABLE_DEPLOY_ID ?? null,
  };
};`;

  if (flavor === "cjs") {
    return `// Generated by faable deploy for this build only — auto-restored afterwards.
// Adds a deterministic buildId (FAABLE_DEPLOY_ID) unless the config defines
// its own generateBuildId. See faable.com docs on version skew.
${originalFile ? `const original = require("./${originalFile}");` : `const original = {};`}
${resolver}
module.exports = (phase, args) => resolveConfig(original, phase, args);
`;
  }
  return `// Generated by faable deploy for this build only — auto-restored afterwards.
// Adds a deterministic buildId (FAABLE_DEPLOY_ID) unless the config defines
// its own generateBuildId. See faable.com docs on version skew.
${originalFile ? `import original from "./${originalFile}";` : `const original = {};`}
${resolver}
export default (phase, args) => resolveConfig(original, phase, args);
`;
};

const packageIsESM = async (workdir: string): Promise<boolean> => {
  try {
    const pkg = JSON.parse(
      await readFile(path.join(workdir, "package.json"), "utf8")
    );
    return pkg.type === "module";
  } catch {
    return false;
  }
};

/**
 * Wraps the project's next.config for the build. Returns null (no-op) when
 * there is nothing to do: FAABLE_DEPLOY_ID absent from `env`, a `.ts` config,
 * or the user already handles the buildId. Callers MUST `await
 * wrapped?.restore()` in a finally.
 */
export const wrap_next_config = async (
  workdir: string,
  env: Record<string, string>
): Promise<WrappedConfig | null> => {
  if (!env.FAABLE_DEPLOY_ID) return null;

  if (existsSync(path.join(workdir, "next.config.ts"))) {
    log.warn(
      `next.config.ts detected — skipping the deterministic buildId wrap (define generateBuildId with FAABLE_DEPLOY_ID yourself to opt in).`
    );
    return null;
  }

  const configFile = CONFIG_FILES.find((f) =>
    existsSync(path.join(workdir, f))
  );

  // Wrapper flavor/extension: mirror the original; with no config at all,
  // .mjs is unambiguous regardless of package.json type.
  let wrapperFile: string;
  let originalFile: string | null = null;
  let flavor: "cjs" | "esm";

  if (!configFile) {
    wrapperFile = "next.config.mjs";
    flavor = "esm";
  } else {
    const ext = path.extname(configFile); // .js | .cjs | .mjs
    originalFile = `${ORIGINAL_PREFIX}${ext}`;
    wrapperFile = configFile;
    flavor =
      ext === ".mjs" || (ext === ".js" && (await packageIsESM(workdir)))
        ? "esm"
        : "cjs";
  }

  const wrapperPath = path.join(workdir, wrapperFile);
  const originalPath = originalFile ? path.join(workdir, originalFile) : null;

  if (configFile && originalPath) {
    await rename(path.join(workdir, configFile), originalPath);
  }
  await writeFile(wrapperPath, wrapperBody(originalFile, flavor), "utf8");
  log.info(
    `🧬 Deterministic buildId: wrapped ${configFile ?? "(no next.config)"} → generateBuildId from FAABLE_DEPLOY_ID`
  );

  // Ctrl-C / SIGTERM mid-build must not leave the user's workdir mutated.
  const restoreSync = () => {
    try {
      rmSync(wrapperPath, { force: true });
      if (configFile && originalPath) {
        renameSync(originalPath, path.join(workdir, configFile));
      }
    } catch {
      // Best effort on the signal path
    }
  };
  process.once("SIGINT", restoreSync);
  process.once("SIGTERM", restoreSync);

  let restored = false;
  return {
    restore: async () => {
      if (restored) return;
      restored = true;
      process.removeListener("SIGINT", restoreSync);
      process.removeListener("SIGTERM", restoreSync);
      await rm(wrapperPath, { force: true });
      if (configFile && originalPath) {
        await rename(originalPath, path.join(workdir, configFile));
      }
    },
  };
};
